version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-repeatly}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack:latest
    restart: always
    environment:
      REDIS_ARGS: --requirepass ${REDIS_PASSWORD:-devpassword123}
    ports:
      - "${REDIS_PORT:-6379}:6379"
      - "${REDIS_INSIGHT_PORT:-8001}:8001" # RedisInsight GUI
    command: redis-server --requirepass ${REDIS_PASSWORD:-devpassword123}
volumes:
  pgdata:
