export const TIMEZONE_OPTIONS = [
  { label: "UTC - Coordinated Universal Time", value: "UTC" },

  { label: "US Eastern (EST/EDT)", value: "America/New_York" },
  { label: "US Central (CST/CDT)", value: "America/Chicago" },
  { label: "US Mountain (MST/MDT)", value: "America/Denver" },
  { label: "US Pacific (PST/PDT)", value: "America/Los_Angeles" },
  { label: "US Alaska (AKST/AKDT)", value: "America/Anchorage" },
  { label: "US Hawaii (HST)", value: "Pacific/Honolulu" },
  { label: "Canada Atlantic (AST/ADT)", value: "America/Halifax" },
  { label: "Canada Central (CST/CDT)", value: "America/Winnipeg" },
  { label: "Canada Eastern (EST/EDT)", value: "America/Toronto" },
  { label: "Canada Mountain (MST/MDT)", value: "America/Edmonton" },
  { label: "Canada Pacific (PST/PDT)", value: "America/Vancouver" },
  { label: "Mexico Central (CST/CDT)", value: "America/Mexico_City" },

  { label: "United Kingdom (GMT/BST)", value: "Europe/London" },
  { label: "Ireland (GMT/IST)", value: "Europe/Dublin" },
  { label: "France (CET/CEST)", value: "Europe/Paris" },
  { label: "Germany (CET/CEST)", value: "Europe/Berlin" },
  { label: "Italy (CET/CEST)", value: "Europe/Rome" },
  { label: "Spain (CET/CEST)", value: "Europe/Madrid" },
  { label: "Netherlands (CET/CEST)", value: "Europe/Amsterdam" },
  { label: "Switzerland (CET/CEST)", value: "Europe/Zurich" },
  { label: "Austria (CET/CEST)", value: "Europe/Vienna" },
  { label: "Poland (CET/CEST)", value: "Europe/Warsaw" },
  { label: "Czech Republic (CET/CEST)", value: "Europe/Prague" },
  { label: "Sweden (CET/CEST)", value: "Europe/Stockholm" },
  { label: "Norway (CET/CEST)", value: "Europe/Oslo" },
  { label: "Denmark (CET/CEST)", value: "Europe/Copenhagen" },
  { label: "Finland (EET/EEST)", value: "Europe/Helsinki" },
  { label: "Greece (EET/EEST)", value: "Europe/Athens" },
  { label: "Romania (EET/EEST)", value: "Europe/Bucharest" },
  { label: "Russia Moscow (MSK)", value: "Europe/Moscow" },
  { label: "Russia Kaliningrad (EET/EEST)", value: "Europe/Kaliningrad" },
  { label: "Ukraine (EET/EEST)", value: "Europe/Kiev" },
  { label: "Turkey (TRT)", value: "Europe/Istanbul" },

  { label: "China (CST)", value: "Asia/Shanghai" },
  { label: "Japan (JST)", value: "Asia/Tokyo" },
  { label: "India (IST)", value: "Asia/Kolkata" },
  { label: "South Korea (KST)", value: "Asia/Seoul" },
  { label: "Singapore (SGT)", value: "Asia/Singapore" },
  { label: "Hong Kong (HKT)", value: "Asia/Hong_Kong" },
  { label: "Taiwan (CST)", value: "Asia/Taipei" },
  { label: "Thailand (ICT)", value: "Asia/Bangkok" },
  { label: "Malaysia (MYT)", value: "Asia/Kuala_Lumpur" },
  { label: "Indonesia Jakarta (WIB)", value: "Asia/Jakarta" },
  { label: "Philippines (PHT)", value: "Asia/Manila" },
  { label: "Vietnam (ICT)", value: "Asia/Ho_Chi_Minh" },
  { label: "UAE (GST)", value: "Asia/Dubai" },
  { label: "Saudi Arabia (AST)", value: "Asia/Riyadh" },
  { label: "Israel (IST/IDT)", value: "Asia/Jerusalem" },
  { label: "Iran (IRST/IRDT)", value: "Asia/Tehran" },
  { label: "Pakistan (PKT)", value: "Asia/Karachi" },
  { label: "Bangladesh (BST)", value: "Asia/Dhaka" },
  { label: "Sri Lanka (SLST)", value: "Asia/Colombo" },
  { label: "Nepal (NPT)", value: "Asia/Kathmandu" },
  { label: "Afghanistan (AFT)", value: "Asia/Kabul" },
  { label: "Kazakhstan Almaty (ALMT)", value: "Asia/Almaty" },
  { label: "Uzbekistan (UZT)", value: "Asia/Tashkent" },

  { label: "Australia Sydney (AEST/AEDT)", value: "Australia/Sydney" },
  { label: "Australia Melbourne (AEST/AEDT)", value: "Australia/Melbourne" },
  { label: "Australia Brisbane (AEST)", value: "Australia/Brisbane" },
  { label: "Australia Perth (AWST)", value: "Australia/Perth" },
  { label: "Australia Adelaide (ACST/ACDT)", value: "Australia/Adelaide" },
  { label: "Australia Darwin (ACST)", value: "Australia/Darwin" },
  { label: "New Zealand (NZST/NZDT)", value: "Pacific/Auckland" },
  { label: "Fiji (FJT/FJST)", value: "Pacific/Fiji" },
  { label: "Guam (ChST)", value: "Pacific/Guam" },

  { label: "Brazil São Paulo (BRT/BRST)", value: "America/Sao_Paulo" },
  { label: "Brazil Brasília (BRT/BRST)", value: "America/Fortaleza" },
  { label: "Argentina (ART)", value: "America/Argentina/Buenos_Aires" },
  { label: "Chile (CLT/CLST)", value: "America/Santiago" },
  { label: "Colombia (COT)", value: "America/Bogota" },
  { label: "Peru (PET)", value: "America/Lima" },
  { label: "Venezuela (VET)", value: "America/Caracas" },
  { label: "Ecuador (ECT)", value: "America/Guayaquil" },
  { label: "Uruguay (UYT/UYST)", value: "America/Montevideo" },
  { label: "Paraguay (PYT/PYST)", value: "America/Asuncion" },
  { label: "Bolivia (BOT)", value: "America/La_Paz" },

  { label: "South Africa (SAST)", value: "Africa/Johannesburg" },
  { label: "Egypt (EET/EEST)", value: "Africa/Cairo" },
  { label: "Nigeria (WAT)", value: "Africa/Lagos" },
  { label: "Kenya (EAT)", value: "Africa/Nairobi" },
  { label: "Morocco (WET/WEST)", value: "Africa/Casablanca" },
  { label: "Algeria (CET)", value: "Africa/Algiers" },
  { label: "Tunisia (CET)", value: "Africa/Tunis" },
  { label: "Ghana (GMT)", value: "Africa/Accra" },
  { label: "Ethiopia (EAT)", value: "Africa/Addis_Ababa" },
  { label: "Tanzania (EAT)", value: "Africa/Dar_es_Salaam" },

  { label: "Iceland (GMT)", value: "Atlantic/Reykjavik" },
  { label: "Azores (AZOT/AZOST)", value: "Atlantic/Azores" },
  { label: "Cape Verde (CVT)", value: "Atlantic/Cape_Verde" },
  { label: "Greenland West (WGT/WGST)", value: "America/Godthab" },
];
