name: Deploy Scheduler Service to Cloud Run

on:
  workflow_dispatch:

env:
  PROJECT_ID: repeatly-dev
  REGION: asia-south1
  REGISTRY: asia-south1-docker.pkg.dev

jobs:
  deploy-scheduler:
    name: Deploy Scheduler Service
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +'%s')" >> $GITHUB_ENV

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.DEV_REPEATLY_ADMIN_SERVICE_ACCOUNT }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Authorize Docker
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      # Run Database Migrations
      - name: Run Database Migrations
        run: |
          docker build -f packages/database/Dockerfile -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-images/repeatly-db-migrate:${{ github.sha }} .
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-images/repeatly-db-migrate:${{ github.sha }}

          # Create or update the migration job
          echo "Creating database migration job..."
          gcloud run jobs create repeatly-db-migrate \
            --image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-images/repeatly-db-migrate:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --set-secrets="DATABASE_URL=database-url:latest" \
            --command="npx,prisma,migrate,deploy" \
            --task-timeout=300s \
            --max-retries=3 \
            --memory=512Mi \
            --cpu=1 \
            --quiet || echo "Job already exists, updating..."

          # If job creation failed, try to update it
          if ! gcloud run jobs describe repeatly-db-migrate --region=${{ env.REGION }} --quiet 2>/dev/null; then
            echo "Job does not exist, creating..."
            gcloud run jobs create repeatly-db-migrate \
              --image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-images/repeatly-db-migrate:${{ github.sha }} \
              --region=${{ env.REGION }} \
              --set-secrets="DATABASE_URL=database-url:latest" \
              --command="npx,prisma,migrate,deploy" \
              --task-timeout=300s \
              --max-retries=3 \
              --memory=512Mi \
              --cpu=1 \
              --quiet
          else
            echo "Job exists, updating..."
            gcloud run jobs update repeatly-db-migrate \
              --image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-images/repeatly-db-migrate:${{ github.sha }} \
              --region=${{ env.REGION }} \
              --set-secrets="DATABASE_URL=database-url:latest" \
              --command="npx,prisma,migrate,deploy" \
              --task-timeout=300s \
              --max-retries=3 \
              --memory=512Mi \
              --cpu=1 \
              --quiet
          fi

          # Execute the migration job
          echo "Executing database migration job..."
          gcloud run jobs execute repeatly-db-migrate \
            --region=${{ env.REGION }} \
            --quiet

          echo "✅ Database migrations completed successfully"

      # Deploy Scheduler Service
      - name: Build and Deploy Scheduler
        run: |
          docker build -f packages/scheduler/Dockerfile -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-images/repeatly-scheduler:${{ github.sha }} .
          docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-images/repeatly-scheduler:${{ github.sha }}

          gcloud run deploy repeatly-scheduler \
            --image=${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/cloud-run-images/repeatly-scheduler:${{ github.sha }} \
            --region=${{ env.REGION }} \
            --no-allow-unauthenticated \
            --min-instances=1 \
            --max-instances=1 \
            --memory=256Mi \
            --timeout=3600 \
            --set-env-vars="NODE_ENV=production" \
            --set-secrets="DATABASE_URL=database-url:latest,REDIS_URL=redis-url:latest" \
            --labels="env=production,service=scheduler,timestamp=${{ env.TIMESTAMP }}"

      - name: Deployment Summary
        run: |
          echo "🚀 Scheduler service deployed successfully!"
          echo "Scheduler: repeatly-scheduler (internal)"
          echo "📋 Deployment completed at: $(date)"
          echo "🔗 Commit: ${{ github.sha }}"
